version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    links:
      - db
    ports:
      - "8079:80"
    volumes:
      - ./api:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - "./docker/.mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_USER: root_adm
      MYSQL_PASSWORD: qwerty123
